sudo: required

language: elixir
elixir:
  - 1.2.5
otp_release:
  - 18.3

branches:
  only:
  - master

cache:
  directories:
  - deps
  - _build

install:
  - curl -sf https://raw.githubusercontent.com/brson/multirust/master/blastoff.sh | sh -s -- --yes
  - mix local.hex --force
  - mix deps.get
  - mix rustler.update_rust

script:
  - mix test

notifications:
  webhooks: http://travis.lunarco.de/mcex
  irc:
    on_success: change
    on_failure: change
    skip_join: true
    channels:
      - "irc.freenode.org#McEx"
    template:
      - "[%{repository_name} %{branch}] %{message} #%{build_number} %{build_url}"
      - "[%{repository_name} %{branch}] %{commit_message} (%{commit} by %{author}) %{compare_url}"
